name: "middleware-server"

services:
  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: middleware-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php


  mysql:
    image: mysql:9.0.1
    container_name: middleware-mysql
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  php:
    build: ./docker/php
    container_name: middleware-php
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env.example
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    volumes:
      - .:/var/www